import { Product } from "@/lib/types";

const grainsProducts: Product[] = [
  {
    id: "g1",
    category: "Café en Grains",
    type: "Spécial",
    name: "Café Spécial",
    description: "Blend signature Finjani Aroma, rond et aromatique, pensé pour une extraction riche en espresso.",
    origin: "Blend Maison",
    price: 34,
    priceNote: "250g",
    variants: [
      { label: "125g", price: 18 },
      { label: "250g", price: 34 },
      { label: "500g", price: 68 },
      { label: "1kg", price: 136 },
    ],
    imageUrl: "/products/cafe-special.jpg",
  },
  {
    id: "g2",
    category: "Café en Grains",
    type: "Moka",
    name: "Café Moka",
    description: "Profil fruité et cacao, inspiré des grands mokas, avec une finale élégante.",
    origin: "Éthiopie",
    price: 37,
    priceNote: "250g",
    variants: [
      { label: "125g", price: 19 },
      { label: "250g", price: 37 },
      { label: "500g", price: 74 },
      { label: "1kg", price: 147 },
    ],
    imageUrl: "/products/cafe-moka.jpg",
  },
  {
    id: "g3",
    category: "Café en Grains",
    type: "Arabia",
    name: "Café Arabia",
    description: "Grains délicats et parfumés pour une tasse soyeuse, notes florales et douceur équilibrée.",
    origin: "Arabia Blend",
    price: 46,
    priceNote: "250g",
    variants: [
      { label: "125g", price: 23 },
      { label: "250g", price: 46 },
      { label: "500g", price: 92 },
      { label: "1kg", price: 184 },
    ],
    imageUrl: "/products/cafe-arabia.jpg",
  },
  {
    id: "g4",
    category: "Café en Grains",
    type: "Marocain",
    name: "Café Marocain",
    description: "Recette inspirée du patrimoine marocain, épices fines et caractère chaleureux.",
    origin: "Maroc",
    price: 40,
    priceNote: "250g",
    variants: [{ label: "250g", price: 40 }],
    imageUrl: "/products/cafe-marocain.jpg",
  },
  {
    id: "g5",
    category: "Café en Grains",
    type: "Arabia Saoudia",
    name: "Café Arabia Saoudia",
    description: "Assemblage oriental premium aux notes de cardamome et safran, intense et raffiné.",
    origin: "Arabie Saoudite",
    price: 62,
    priceNote: "250g",
    variants: [{ label: "250g", price: 62 }],
    imageUrl: "/products/cafe-arabia-saoudia.jpg",
  },
  {
    id: "g6",
    category: "Café en Grains",
    type: "Chamia",
    name: "Café Chamia",
    description: "Sélection d'inspiration levantine, épicée et profonde, pour les amateurs de profils rares.",
    origin: "Levant",
    price: 94,
    priceNote: "250g",
    variants: [{ label: "250g", price: 94 }],
    imageUrl: "/products/cafe-chamia.jpg",
  },
];

const gelatoProducts: Product[] = [
  {
    id: "gel1",
    category: "Gelato Italiano",
    type: "Vanille",
    name: "Gelato Vanille",
    description: "Vanille premium à texture dense et crémeuse, finition douce et élégante.",
    origin: "Atelier Finjani",
    price: 15,
    imageUrl: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "gel2",
    category: "Gelato Italiano",
    type: "Pistache",
    name: "Gelato Pistache",
    description: "Pistache torréfiée au style italien, goût intense et texture veloutée.",
    origin: "Italie",
    price: 17,
    imageUrl: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "gel3",
    category: "Gelato Italiano",
    type: "Chocolat",
    name: "Gelato Chocolat",
    description: "Cacao riche et profond, parfait pour une expérience dessert premium.",
    origin: "Atelier Finjani",
    price: 16,
    imageUrl: "https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "gel4",
    category: "Gelato Italiano",
    type: "Fraise",
    name: "Gelato Fraise",
    description: "Fraise gourmande et fraîche, équilibrée entre fruité vif et onctuosité.",
    origin: "Atelier Finjani",
    price: 16,
    imageUrl: "https://images.unsplash.com/photo-1488900128323-21503983a07e?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "gel5",
    category: "Gelato Italiano",
    type: "Mangue",
    name: "Gelato Mangue",
    description: "Mangue tropicale et texture artisanale, une touche exotique haut de gamme.",
    origin: "Atelier Finjani",
    price: 17,
    imageUrl: "https://images.unsplash.com/photo-1528825871115-3581a5387919?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "gel6",
    category: "Gelato Italiano",
    type: "Noisette",
    name: "Gelato Noisette",
    description: "Noisette grillée au profil gourmand et raffiné, texture fondante.",
    origin: "Italie",
    price: 18,
    imageUrl: "https://images.unsplash.com/photo-1616920673171-2f7ee3537d0f?auto=format&fit=crop&w=900&q=80",
  },
];

const tartesGlaceesProducts: Product[] = [
  {
    id: "tg1",
    category: "Tartes Glacées",
    type: "Chocolat",
    name: "Tarte Glacée Chocolat",
    description: "Cœur glacé chocolat noir et biscuit fin, finition premium signée Finjani.",
    origin: "Atelier Finjani",
    price: 140,
    priceNote: "8 parts",
    imageUrl: "https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "tg2",
    category: "Tartes Glacées",
    type: "Pistache",
    name: "Tarte Glacée Pistache",
    description: "Création glacée pistache, élégante et généreuse, idéale pour vos célébrations.",
    origin: "Atelier Finjani",
    price: 155,
    priceNote: "8 parts",
    imageUrl: "https://images.unsplash.com/photo-1602351447937-745cb720612f?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "tg3",
    category: "Tartes Glacées",
    type: "Vanille",
    name: "Tarte Glacée Vanille",
    description: "Vanille de Madagascar et texture glacée soyeuse, style minimal chic.",
    origin: "Atelier Finjani",
    price: 145,
    priceNote: "8 parts",
    imageUrl: "https://images.unsplash.com/photo-1464306076886-da185f6a9d05?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "tg4",
    category: "Tartes Glacées",
    type: "Signature",
    name: "Signature Praliné Café",
    description: "Création dessert signature au praliné café, pensée pour une expérience luxueuse.",
    origin: "Atelier Finjani",
    price: 170,
    priceNote: "8 parts",
    imageUrl: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=900&q=80",
  },
];

export const sampleProducts: Product[] = [
  ...grainsProducts,
  ...gelatoProducts,
  ...tartesGlaceesProducts,
];

export { grainsProducts, gelatoProducts, tartesGlaceesProducts };
